CLOUD_COMMAND_RULES: dict[str, dict[str, set[str]]] = {
    "codex": {
        "subcommands": {
            "app-server",
            "apply",
            "cloud",
            "completion",
            "debug",
            "exec",
            "features",
            "help",
            "login",
            "logout",
            "mcp",
            "mcp-server",
            "review",
            "sandbox",
        },
        "flags": {"-h", "--help", "-V", "--version"},
        "value_flags": {
            "-C",
            "-a",
            "-c",
            "-i",
            "-m",
            "-p",
            "-s",
            "--add-dir",
            "--ask-for-approval",
            "--cd",
            "--config",
            "--disable",
            "--enable",
            "--image",
            "--local-provider",
            "--model",
            "--profile",
            "--sandbox",
        },
    },
    "claude": {
        "subcommands": {
            "agents",
            "auth",
            "auto-mode",
            "doctor",
            "install",
            "mcp",
            "plugin",
            "plugins",
            "setup-token",
            "update",
            "upgrade",
        },
        "flags": {
            "-h",
            "--help",
            "-p",
            "--print",
            "-v",
            "--version",
            "--include-partial-messages",
            "--no-session-persistence",
            "--replay-user-messages",
        },
        "terminal_value_flags": {
            "--fallback-model",
            "--input-format",
            "--json-schema",
            "--max-budget-usd",
            "--output-format",
        },
        "value_flags": {
            "--add-dir",
            "--agent",
            "--agents",
            "--allowed-tools",
            "--allowedTools",
            "--append-system-prompt",
            "--betas",
            "--debug-file",
            "--disallowed-tools",
            "--disallowedTools",
            "--effort",
            "--file",
            "--json-schema",
            "--mcp-config",
            "--model",
            "--name",
            "--output-format",
            "--permission-mode",
            "--plugin-dir",
            "--session-id",
            "--setting-sources",
            "--settings",
            "--system-prompt",
            "--tools",
            "--input-format",
            "--fallback-model",
            "--max-budget-usd",
            "-n",
        },
    },
}