CLOUD_COMMAND_RULES: dict[str, dict[str, set[str]]] = {
    "codex": {
        "subcommands": {
            "app-server",
            "apply",
            "cloud",
            "completion",
            "debug",
            "exec",
            "features",
            "help",
            "login",
            "logout",
            "mcp",
            "mcp-server",
            "review",
            "sandbox",
        },
        "flags": {"-h", "--help", "-V", "--version"},
        "value_flags": {
            "-C",
            "-a",
            "-c",
            "-i",
            "-m",
            "-p",
            "-s",
            "--add-dir",
            "--ask-for-approval",
            "--cd",
            "--config",
            "--disable",
            "--enable",
            "--image",
            "--local-provider",
            "--model",
            "--profile",
            "--sandbox",
        },
    },
    "claude": {
        "subcommands": {
            "agents",
            "auth",
            "auto-mode",
            "doctor",
            "install",
            "mcp",
            "plugin",
            "plugins",
            "setup-token",
            "update",
            "upgrade",
        },
        "flags": {
            "-h",
            "--help",
            "-p",
            "--print",
            "-v",
            "--version",
            "--include-partial-messages",
            "--no-session-persistence",
            "--replay-user-messages",
        },
        "terminal_value_flags": {
            "--fallback-model",
            "--input-format",
            "--json-schema",
            "--max-budget-usd",
            "--output-format",
        },
        "value_flags": {
            "--add-dir",
            "--agent",
            "--agents",
            "--allowed-tools",
            "--allowedTools",
            "--append-system-prompt",
            "--betas",
            "--debug-file",
            "--disallowed-tools",
            "--disallowedTools",
            "--effort",
            "--file",
            "--json-schema",
            "--mcp-config",
            "--model",
            "--name",
            "--output-format",
            "--permission-mode",
            "--plugin-dir",
            "--session-id",
            "--setting-sources",
            "--settings",
            "--system-prompt",
            "--tools",
            "--input-format",
            "--fallback-model",
            "--max-budget-usd",
            "-n",
        },
    },
}


COMPILE_LANGUAGE_CONFIGS: dict[str, dict[str, object]] = {
    "c": {
        "label": "C",
        "default_extension": "",
        "supports_optimization": True,
        "optimization_label": "Optimize (-O2)",
        "supports_warnings": True,
        "warning_label": "Extra warnings (-Wall -Wextra)",
    },
    "cpp": {
        "label": "C++",
        "default_extension": "",
        "supports_optimization": True,
        "optimization_label": "Optimize (-O2)",
        "supports_warnings": True,
        "warning_label": "Extra warnings (-Wall -Wextra)",
    },
    "go": {
        "label": "Go",
        "default_extension": "",
        "supports_optimization": False,
        "optimization_label": None,
        "supports_warnings": False,
        "warning_label": None,
    },
    "java": {
        "label": "Java",
        "default_extension": ".jar",
        "supports_optimization": False,
        "optimization_label": None,
        "supports_warnings": True,
        "warning_label": "Lint warnings (-Xlint)",
    },
    "rust": {
        "label": "Rust",
        "default_extension": "",
        "supports_optimization": True,
        "optimization_label": "Optimize (-O)",
        "supports_warnings": False,
        "warning_label": None,
    },
    "csharp": {
        "label": "C#",
        "default_extension": ".exe",
        "supports_optimization": True,
        "optimization_label": "Optimize (-optimize+)",
        "supports_warnings": True,
        "warning_label": "Higher warning level (-warn:4)",
    },
}